name: CI con Escaneo de Código
on:
  workflow_dispatch:     # permite ejecutarlo manualmente
  push:
    branches: [main] # Se ejecuta cada vez que haces un push a la rama main
  pull_request:
    branches: [main] # También en pull requests

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npx eslint .
  
